### PR TITLE
update

### PR DESCRIPTION
**Pull request by Lokeshsri11**

### CODE REVIEW

**Comment by prateek041** [comment]
@Lokeshsri11 cards are stretched out. fix their max-width and height. card should be long not wide.

Also, in layout.jsx, put the max-width to be fixed, Push the changes I will review.

**Comment by Lokeshsri11** [comment]
> @Lokeshsri11 cards are stretched out. fix their max-width and height. card should be long not wide.
> 
> Also, in layout.jsx, put the max-width to be fixed, Push the changes I will review.

now check @prateek041

**Comment by prateek041** [comment]
Make your magic work Lokesh ! Make the cards look beautiful please.
@Lokeshsri11

**Comment by Lokeshsri11** [comment]
> Make your magic work Lokesh ! Make the cards look beautiful please. @Lokeshsri11

what about now?

**Comment by prateek041** [comment]
Check this one: https://imbue.com/company/ their company page. Can we make it something like this ?
@Lokeshsri11

**Comment by prateek041** [comment]
lgtm, I will fix from here.

**Pull request merged**
